// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<proto.s2c.push> (proto.s2c.push.Tag);
		Protocol.SetRequest<SprotoType.proto.s2c.push.request> (proto.s2c.push.Tag);

	}

	public class proto {
		public class s2c {
			public class push {
				public const int Tag = 1;
			}

		}

	}

}